### ISSUE TITLE
Parameter 'browser' is required by BeforeTest on method SetPropertyandopenBrowser but has not been marked @Optional or defined

### ISSUE THREAD

**Issue by Ojasadi** [browserstack/testng-browserstack#23]
I am trying  to run same test cases in different browser. Can anybody help what is wrong in this

Error:
Parameter 'browser' is required by BeforeTest on method SetPropertyandopenBrowser but has not been marked @Optional or defined

package mytestngpackage;

import org.testng.annotations.Test;
import org.testng.Assert;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;

public class MultipleBrowser {

	WebDriver DR;
	//String browser;
		
@BeforeTest
@Parameters("browser")

 public void SetPropertyandopenBrowser(String browser) {
	
	if(browser.equalsIgnoreCase("Chrome")) {
		System.setProperty("webdriver.chrome.driver","C:\\Users\\14049\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
		DR=new ChromeDriver();
	}
	else if(browser.equalsIgnoreCase("Edge")) {
		System.setProperty("webdriver.edge.driver", "C:\\Users\\14049\\Desktop\\Selenium\\edgedriver_win64\\msedgedriver.exe");
		DR=new EdgeDriver() ;
	}	
	DR.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
}

@Test(priority = 1)
public void openurl() {
	DR.get("https://mail.rediff.com/cgi-bin/login.cgi");
	String Actual= DR.getTitle(); //to know the title of webpage
	Assert.assertEquals(Actual,"Rediffmail");
	
}

@Test(priority = 2,dependsOnMethods = "openurl")
public void enterusername() {
	DR.findElement(By.name("login")).sendKeys("abc@rediffmail.com");
}
@Test(priority=3,dependsOnMethods = "enterusername")
public void enetrpassword() {
	DR.findElement(By.id("password")).sendKeys("12345");
}

}

**Comment by shawnlobo96** [comment]
The issue seems to be similar to https://github.com/browserstack/testng-browserstack/issues/10

@Ojasadi can you take a look at it?

**Comment by Ojasadi** [comment]
Ya...got it...Issue Resolved. Thanks
